### ISSUE TITLE
Prepare for first release under Microsoft

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-gradle#889]
Below is a checklist to do before we shipped this extension on behalf of Microsoft:

Repo:
- [x] rename `master` to `main` #893
- [x] configure branch protection rules
- [x] update publisher id in package.json #899 
- [x] add Application Inisight key in package.json #899 

Pipelines:
- [x] fix CI in GitHub Action #890 
- [x] remove publish pipelines in GitHub Action #898 
- [x] setup CI/CD piplines in Azure Pipeline #902 
- [x] setup RC pipeline in Azure DevOps #907 

Telemetry:
- [x] add telemetry part in README #908 
- [x] add basic telemetry events #909 

TODO items:
~~set up pipeline to publish api to npm~~ Currently we have no plan for npm module
