### ISSUE TITLE
Support Gradle Authoring features

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-gradle#956]
feature branch: cs-authoring-branch

- [x] A standalone (Groovy/Gradle) Language Server #959
- [x] Basic Syntax Highlighting #960 
- [x] Semantic Highlighting #967 
- [x] Outline providing #969 
- [x] Diagnostics Publishing #962 
- [x] Basic Auto Completion #971
- [x] Dependency completion #970
